name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
